[build]
  base    = "frontend"   # ← Netlify Base dir
  command = "npm run build"
  publish = "dist"

# JS/CSS 올바른 MIME
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# SPA 라우팅 + API 프록시(있다면)
[[redirects]]
  from = "/api/*"
  to   = "https://api.mayservice.co.kr/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
[build.environment]
  NODE_VERSION = "20"
